server:
  port: 8081
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/physmath_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
gigachat:
  auth-url: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
  api-url: https://gigachat.devices.sberbank.ru/api/v1/chat/completions
  client-id: ${GIGACHAT_CLIENT_ID:a7449a49-f68b-4b03-ab7f-1b070d124d35}
  client-secret: ${GIGACHAT_CLIENT_SECRET:YTc0NDlhNDktZjY4Yi00YjAzLWFiN2YtMWIwNzBkMTI0ZDM1OjZkNGVlN2RlLTk1NTktNGQ3My1iOWNlLWM1OTNlNTFlN2I4Ng==}